// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8q90e1zeUSJW6p2YzgrFhfsNWbXth320',
    appId: '1:140959539480:android:2ad96a330a3e3b115ebe6d',
    messagingSenderId: '140959539480',
    projectId: 'petinder-643dc',
    databaseURL:
        'https://petinder-643dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petinder-643dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeu-JbNYvqiTFHk3JA9cbmXT0BadeHF-0',
    appId: '1:140959539480:ios:80d3404ea5da1a445ebe6d',
    messagingSenderId: '140959539480',
    projectId: 'petinder-643dc',
    databaseURL:
        'https://petinder-643dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petinder-643dc.appspot.com',
    iosClientId:
        '140959539480-etikiss6e0jkg539q8b0coll1uhjdaof.apps.googleusercontent.com',
    iosBundleId: 'com.example.petinder',
  );
}
